### PR TITLE
EFECTReport type and standards

### PR DESCRIPTION
**Pull request by dilpath**
Currently the example usage for `EFECTReport` is in a comment at the end of `efect_report.py`. This should be moved to the documentation somewhere, e.g. one of the example notebooks. Let me know if you have a suggestion.

### CODE REVIEW

**Review by tjsego — CHANGES_REQUESTED** [review]
Looks great! At some point we'll likely migrate the generated schemas out of the python source code, but for now I think it's fine. So just a few minor revisions:

Are you planning on distributing mkstd on conda? If not, can you revise the added dependency in env.yml to use pip, as in [this example](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#activating-an-environment:~:text=numpy%0A%20%20%2D%20pandas-,EXAMPLE,-%3A%20A%20more%20complex)?

Also, can you update the requirements in setup.py?

**Comment by dilpath** [comment]
> Looks great! At some point we'll likely migrate the generated schemas out of the python source code, but for now I think it's fine. So just a few minor revisions:

Sounds good, let me know if I can help at that point.

> Are you planning on distributing mkstd on conda?

Currently no plan as I don't use it myself. I do not see a benefit for my own work, but can if it helps libSSR in any way.

> If not, can you revise the added dependency in env.yml to use pip, as in [this example](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#activating-an-environment:~:text=numpy%0A%20%20%2D%20pandas-,EXAMPLE,-%3A%20A%20more%20complex)?
> Also, can you update the requirements in setup.py?

Thanks, done now, and I locally tested that installation with "setup.py" now works for me. I changed the code used to detect the location of the version file to something that works for me, and in my experience generally works on every system. Let me know if you see an issue though, I can revert that and try to get the previous code with `os` working for me too.

**Comment by dilpath** [comment]
In light of the manuscript, I can see that it probably makes sense to rename `class SSRData` to `class EFECTReport` as you have it in the `port` branch. I'm happy to to do this, let me know.

**Comment by tjsego** [comment]
> In light of the manuscript, I can see that it probably makes sense to rename `class SSRData` to `class EFECTReport` as you have it in the `port` branch. I'm happy to to do this, let me know.

Yes, this makes sense. Otherwise, this looks great. After this refactoring, we can merge this PR.

**Comment by dilpath** [comment]
> > In light of the manuscript, I can see that it probably makes sense to rename `class SSRData` to `class EFECTReport` as you have it in the `port` branch. I'm happy to to do this, let me know.
> 
> Yes, this makes sense. Otherwise, this looks great. After this refactoring, we can merge this PR.

Great, done now. A suggestion from my side would be to make the report level and version a required field. This might have some headache later. If so, I can do this in another PR.

**Pull request merged**
